apiVersion: edp.epam.com/v1alpha1
kind: Codebase
metadata:
  name: test-npm
spec:
  lang: "Javascript"
  framework: "React"
  buildTool: "NPM"
  strategy: "create"
  git:
    url: "https://git.epam.com/epmd-edp/examples/basic/edp-react-helloworld.git"
  route:
    site: "helloworld"
    path: "/api"
status:
  status: "initialized"
  available: false
  LastTimeUpdated: 0001-01-01T00:00:00Z