apiVersion: v2.edp.epam.com/v1alpha1
kind: GitServer
metadata:
  name: test-server
spec:
  gitHost: "https://git.epam.com"
  gitUser: "git user name"
  httpsPort: 443
  sshPort: 58291
  nameSshKeySecret: "secret name"
  createCodeReviewPipeline: false
status:
  status: "initialized"
  available: false
  LastTimeUpdated: 0001-01-01T00:00:00Z