apiVersion: v2.edp.epam.com/v1alpha1
kind: Codebase
metadata:
  labels:
    app.kubernetes.io/name: codebase
    app.kubernetes.io/instance: codebase-sample
    app.kubernetes.io/part-of: edp-codebase-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: edp-codebase-operator
  name: codebase-sample
spec:
  # TODO(user): Add fields here
